# This file is a template, and might need editing before it works on your project.
# Explanation on the scripts:
# https://gitlab.com/gitlab-examples/kubernetes-deploy/blob/master/README.md
image: registry.gitlab.com/gitlab-examples/kubernetes-deploy

variables:
  # Application deployment domain
  # KUBE_DOMAIN: domain.example.com

stages:
  - build
  - test
  - doc
  - review
  - staging
  - canary
  - promotion
  - cleanup
  - production

build:
  stage: build
  script:
    - command build
  only:
    - branches

UAT:
  stage: promotion
  script:
    - command deploy
  environment:
    name: prodblue
    url: http://$CI_PROJECT_PATH_SLUG-prod-blue.$KUBE_DOMAIN
  #when: manual


Performance:
  stage: promotion
  script:
    - command deploy
  environment:
    name: prodgreen
    url: http://$CI_PROJECT_PATH_SLUG-green.$KUBE_DOMAIN
  #when: manual

    
Final Production:
  stage: production
  script:
    - command deploy
  environment:
    name: f_production
    url: http://$CI_PROJECT_PATH_SLUG-production.$KUBE_DOMAIN
  when: manual


sast:
  stage: test 
  script:
    - exit 0

rspec-mysql-unit-test:
  stage: test
  script:
    - exit 0

rspec-postgres-unit-test:
  stage: test
  script:
    - exit 0
    
coveralls-integration-test:
  stage: test
  script:
    - exit 0

simplecov-code-coverage:
  stage: test
  script:
    - exit 0

cucumber-mysql-acceptance-test:
  stage: test
  script:
    - exit 0

cucumber-postgres-acceptance-test:
  stage: test
  script:
    - exit 0

rubocop-static-analysis-test:
  stage: test
  script:
    - exit 0

tanuki-docs:
  stage: doc
  script:
    - exit 0